BulkSMSWebApp/Models/Contacto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BulkSMSWebApp.Models
{
    public class Contacto
    {
        public int ContactoID { get; set; }

        [Required(ErrorMessage="El campo Nombres es requerido")]
        [MaxLength(36, ErrorMessage = "El texto ingresado excede el límite de caractéres permitidos")]
        [MinLength(3, ErrorMessage = "El Nombre debe tener al menos 3 caracteres")]
        public String Nombres { get; set; }

        [Required(ErrorMessage = "El campo Apellidos es requerido")]
        [MinLength(3, ErrorMessage = "El Apellido debe tener al menos 3 caracteres")]
        [MaxLength(36, ErrorMessage = "El texto ingresado excede el límite de caractéres permitidos")]
        public String Apellidos { get; set; }

        [MaxLength(36, ErrorMessage = "El texto ingresado excede el límite de caractéres permitidos")]
        [EmailAddress(ErrorMessage = "El Email ingresado no tiene el formato correcto")]
        public String Email { get; set; }

        [Required(ErrorMessage = "Campo Requerido")]
        [Display(Name = "Estado")]
        public int EstadoID { get; set; }

        [Display(Name = "Departamento")]
        public int? DepartamentoID { get; set; }

        [Display(Name = "Nombre Completo")]
        public String NombreCompleto
        {
            get
            {
                return Nombres + " " + Apellidos;
            }
        }

        // Propiedades de Navegacioon
        public virtual Estado Estado { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Telefono> Telefonos { get; set; }

    }
}

BulkSMSWebApp/Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BulkSMSWebApp.DAL;
using BulkSMSWebApp.Models;
using BulkSMSWebApp.Helpers;
using BulkSMSWebApp.ViewModels;

namespace BulkSMSWebApp.Controllers
{
    public class ContactoController : BaseController
    {
        private BulkSMSContext db = new BulkSMSContext();


        private bool numberExist(String number)
        {
            Boolean flag = false;

            var result = db.Telefonos.Where(c => c.NumeroTel == number).Select(c => c.NumeroTel).Count();

            if (result >= 1)
            {
                flag = true;
            }

            return flag;
        }


        private bool numberExist(string number, int contactoID)
        {

            bool flag = false;

            var result = from t in db.Telefonos
                         where (t.NumeroTel == number && t.ContactoID != contactoID)
                         select t.NumeroTel;

            if (result.Count() >= 1)
            {
                flag = true;
            }
            return flag;
        }
        //public PartialViewResult GetTelephones(int? id)
        //{
        //    var viewModel = new ContactoCelGrupo();
        //    if (Request.IsAjaxRequest())
        //    {
        //        if (id != null)
        //        {
        //            ViewBag.ContactoID = id.Value;
        //            viewModel.Telefonos = viewModel.Contactos.Where(i => i.ContactoID == id.Value).Single().Telefonos;
                    
        //            return PartialView("_TelefonosContacto", viewModel);
        //        }
        //    }

        //    return PartialView();
        //}

        // GET: Contacto
        [NoCache]
        [Authorize]
        public ActionResult Index(int? id)
        {

            var viewModel = new ContactoCelGrupo();

            viewModel.Contactos = db.Contactos.Include(c => c.Departamento).Include(c => c.Estado).OrderByDescending(c => c.Nombres);


            if (Request.IsAjaxRequest())
            {
                if (id != null)
                {
                    ViewBag.ContactoID = id.Value;
                    viewModel.Telefonos = viewModel.Contactos.Where(i => i.ContactoID == id.Value).Single().Telefonos;
                    System.Threading.Thread.Sleep(2000);
                    return PartialView("_TelefonosContacto", viewModel);

                }
            }

            return View(viewModel);
        }





        // GET: Contacto/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Contacto contacto = db.Contactos.Find(id);


        //    if (contacto == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.id = id;
        //    return PartialView("_DetalleContacto", contacto);
        //}

        // GET: Contacto/Create
        [NoCache]
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.DepartamentoID = new SelectList(db.Departamentos.ToList(), "DepartamentoID", "NombreDepartameto");
            ViewBag.EstadoID = new SelectList(db.Estados, "EstadoID", "NombreEstado");
            ViewData["Titulo"] = "Create";
            return View();
        }

        // POST: Contacto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [NoCache]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/*[Bind(Include = "ContactoID,Nombres,Apellidos,Email,DepartamentoID")]*/CreateEditContacto contacto)
        {
            if (ModelState.IsValid)
            {
                bool band = false;
                string num = "";

                //recorremos la lista de números
                foreach (var tel in contacto.Telefonos)
                {
                    //Si el número no viene con el prefijo +505 entonces se lo agregamos
                    if (tel.NumeroTel.ToString().Substring(0, 4) != "+505")
                    {
                        tel.NumeroTel = "+505" + tel.NumeroTel;
                    }

                    // Verificamos que ninguno de los numeros se encuentre registrado en la BD.
                    // Si alguno está registrado se cancela todo y se muestra una alerta
                    if (numberExist(tel.NumeroTel))
                    {
                        num = tel.NumeroTel;
                        Danger(String.Format("El Número <b>{0}</b> ya se encuentra registrado. Por favor provea un número diferente", num), true);
                        ViewBag.DepartamentoID = new SelectList(db.Departamentos.ToList(), "DepartamentoID", "NombreDepartameto");
                        return View(contacto);
                    }
                    else
                    {
                        // una vez que verificamos ningún número de la lista se encuentra registrado
                        // la bandera la hacemos verdadera.
                        band = true;
                    }
                }

                // Si la bandera es verdadera podemos proceder a guardar el contacto y sus números
                if (band)
                {
                    contacto.Contactos.EstadoID = 1; // Activo
                    db.Contactos.Add(contacto.Contactos);
                    db.SaveChanges();

                    // una vez que guardamos el contacto procedemos a guardar los teléfonos asociados a este.
                    foreach (var tel in contacto.Telefonos)
                    {
                        var id = contacto.Contactos.ContactoID;
                        tel.ContactoID = id;
                        db.Telefonos.Add(tel);
                        db.SaveChanges();
                    }

                    //Mostramos una alerta de éxito.
                    Information(String.Format("El Contacto <b>{0}</b> fué agregado correctamente.", contacto.Contactos.Nombres), true);
                    return RedirectToAction("Index");
                }
                else
                {
                    Danger(String.Format("El Número <b>{0}</b> ya se encuentra registrado. Por favor provea un número diferente", num), true);
                    ViewBag.DepartamentoID = new SelectList(db.Departamentos.ToList(), "DepartamentoID", "NombreDepartameto");
                    ViewBag.EstadoID = new SelectList(db.Estados, "EstadoID", "NombreEstado", contacto.Contactos.EstadoID);
                    return View(contacto);
                }

            }
            Danger("Error de Validación, verifica los datos e intenta nuevamente");
            ViewBag.DepartamentoID = new SelectList(db.Departamentos.ToList(), "DepartamentoID", "NombreDepartameto");
            ViewBag.EstadoID = new SelectList(db.Estados, "EstadoID", "NombreEstado", contacto.Contactos.EstadoID);
            return View(contacto);
        }

        // GET: Contacto/Edit/5
        [Authorize]
        [NoCache]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contacto contacto = db.Contactos.Find(id);

            if (contacto == null)
            {
                return HttpNotFound();
            }
            //ViewBag.ContactoID = new SelectList(db.Contactos.Where(c => c.EstadoID == 1), "ContactoID", "NombreCompeto");
            //ViewBag.DepartamentoID = new SelectList(db.Departamentos, "DepartamentoID", "NombreDepartameto");

            //populateTelefonosDropDownList(contacto, contacto.Telefonos);
            PopulateDepartmentsDropDownList(contacto.DepartamentoID);
            ViewBag.EstadoID = new SelectList(db.Estados, "EstadoID", "NombreEstado", contacto.EstadoID);
            return View(contacto);
        }

        // POST: Contacto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [NoCache]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "ContactoID,Nombres,Apellidos,Email,DepartamentoID")] Contacto contacto, List<Telefono> Tels)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    bool band = false;
                    string num = "";
                    //recorremos la lista de números para verificar que ninguno de los números de la lista entrante se encuentre registrados
                    //y que pertenezcan a otro contacto.
                    foreach (var tel in Tels)
                    {
                        //Si el número no viene con el prefijo +505 entonces se lo agregamos
                        if (tel.NumeroTel.ToString().Substring(0, 4) != "+505")
                        {
                            tel.NumeroTel = "+505" + tel.NumeroTel;
                        }
                        // verificamos que los números ingresados no existan en la BD relacionados con otro contacto
                        // si algunno de los números ingresados ya pertenece a otro contacto se muestra una alerta y no se guardan los cambios.
                        if (numberExist(tel.NumeroTel, contacto.ContactoID))
                        {
                            num = tel.NumeroTel;
                            band = false;
                            PopulateDepartmentsDropDownList(contacto.DepartamentoID);

BulkSMSWebApp/Views/Contacto/Activar.cshtml
@model BulkSMSWebApp.Models.Contacto

@{
    ViewBag.Title = "Activar";
}

<h2>Activar</h2>

<h3>¿Confirma que desea Activar el Registro Seleccionado?</h3>
<div>
    <h4>Contacto</h4>
    <hr />
   
    @Html.Partial("_DeleteDetail", Model)

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirmar" class="btn btn-success" /> |
            @Html.ActionLink("Volver", "Index")
        </div>
    }
</div>

BulkSMSWebApp/Views/Contacto/Edit.cshtml
@model BulkSMSWebApp.Models.Contacto

@{
    ViewBag.Title = "Editar Contacto";
}

<script type="text/javascript">

    // Función para eliminar la fila de la tabla
    function borrarFila(obj) {
        $(obj).closest('tr').remove();
        return false;
    }

    $(document).ready(function () {
        var tabla = document.getElementById("myTable");  //obtenemos la tabla con el id = myTable
        var fila = tabla.rows; // obtenemos las filas de la tabla
        var columna = tabla.cells; // obtenemos las columnas de la tabla
        var cont = 0;

        //Event Handler que se activa cuando clickamos el botón Actualizar
        $("#btnActualizar").on("click", function (e) {
            var listName = "Tels";
            var qtd = 0;

            //Si la tabla solo contiene la fila del header (no hay datos), evitamos que envíe el submit a través de e.preventDefault y mostramos una alerta.
            if (fila.length === 1) {
                e.preventDefault();
                alert("ERROR!! No se puede proceder a guardar debido a que no hay ningún teléfono agregado!! \n \nPor favor ingrese al menos un número de teléfono e intente nuevamente");
            }
            else { // Si hay datos entonces obtenemos la lista de telefonos y a través de la función prepend le mandamos esa lista como parametro al
                // al form que tiene la clase .form-horizontal y así se manda la lista al controller.
                $("#myTable > tbody > tr").each(function () {
                    var telefono = $(tabla.rows.item(qtd + 1).cells[0]).find('input').val();
                    var regex = new RegExp("^([+][5][0][5])?[2|5|8|7][0-9]{7}$"); //Definimos la expresión regular

                    if (!regex.test(telefono)) // si uno de los teléfonos ingresados no corresponde con la expresion regular, mandamos una alerta y enfocamos el elemento.
                    {
                        e.preventDefault();
                        alert("Error!! El Teléfono ingresado no es válido. \n\nPor favor provee un número telefónico válido e intenta nuevamente");
                        $(tabla.rows.item(qtd + 1).cells[0]).find('input').focus();
                    }

                    var tipoTel = $(tabla.rows.item(qtd + 1).cells[1]).find('*').val();
                    var id = $(this).attr("id");
                    var descripcion;
                    switch (tipoTel)
                    {
                        case "1":
                            descripcion = "Móvil Móvistar";
                            break;

                        case "2":
                            descripcion = "Móvil Claro";
                            break;

                        case "3":
                            descripcion = "Planta Móvistar";
                            break;

                        case "4":
                            descripcion = "Planta Claro";
                            break;

                        default: { descripcion = tipoTel; break; }
                    }
                    //$(".form-horizontal").prepend("<input type='hidden' name='" + listName + "[" + qtd + "].TelefonoID' value='" + id + "'>");
                    $(".form-horizontal").prepend("<input type='hidden' name='" + listName + "[" + qtd + "].NumeroTel' value='" + telefono + "'>");
                    $(".form-horizontal").prepend("<input type='hidden' name='" + listName + "[" + qtd + "].Descripcion' value='" + descripcion + "'>");
                    qtd += 1;
                });
            }
        });

        //Event Handler que se activa cuando clickamos el botón agregar.
        $("#btnAgregar").on("click", function () {
            var textbox = "<input class='form-control text-center' type='text'>"; //El textbox a agregar para el Número de Telefono

            //El select o dropdpwn a agregar para el campo tipo-telefono
            var select = "<select class='form-control' name='TipoTelefono'><option value='1'>Móvil Móvistar</option><option value='2'>Móvil Claro</option><option value='3'>Planta Móvistar</option><option value='4'>Planta Claro</option></select>";

            // El enlace o botón a agregar para la opción remover, al clickar este hace un llamado a la funcion borrar fila
            var enlace = "<button type='button' class='btn btn-warning' onClick='return borrarFila(this);'><span class='fa fa-trash-o'></span> Remover </button>"

            // Si la tabla solo tiene la fila del header agregar el contenido sin verificar
            if (fila.length <= 1) {
                $("#myTable > tbody").append("<tr id=''><td class='text-center'>" + textbox + "</td><td class='text-center'>" + select + "</td><td class='text-center'>" + enlace + "</td></tr>");
                cont++;
            }
            else // Si la tabla ya tiene mas que la fila del header (tiene datos) hay que verificar que el campo telefono no esté vacío
                // que además tenga el formato correcto de telefono utilizado mediante la expresion regular.
            {
                var regex = new RegExp("^([+][5][0][5])?[2|5|8|7][0-9]{7}$"); //Definimos la expresión regular
                var valor = $(tabla.rows.item(fila.length-1).cells[0]).find('input').val(); //obtenemos el valor del textbox dentro de la primera columna de la ultima fila de la tabla
                if (valor == "") {  // Si está vacío mandamos una alerta para que lo ingrese y evitamos que siga la ejecución haciendo el llamado a return.
                    alert("Error!! No se ha ingresado el número de teléfono \n \nPor favor provee un número de teléfono e intenta nuevamente");
                    $(tabla.rows.item(fila.length-1).cells[0]).find('input').focus();
                    return;
                }
                if (!regex.test(valor)) // si el valor ingresado no corresponde con la expresion regular, mandamos una alerta y enfocamos el elemento.
                {

                    alert("Error!! El Teléfono ingresado no es válido. \n\nPor favor provee un número telefónico válido e intenta nuevamente");
                    $(tabla.rows.item(fila.length - 1).cells[0]).find('input').focus();
                    return;
                }

                // sin las validaciones se pasaron correctamente entonces agregamos una nueva fila a la tabla con el textbox, el select y el botón que anteriormente definimos.
                $("#myTable > tbody").append("<tr id=''><td class='text-center'>" + textbox + "</td><td class='text-center'>" + select + "</td><td class='text-center'>" + enlace + "</td></tr>");
                $(tabla.rows.item(fila.length - 1).cells[0]).find('input').focus();
                cont++;
            }
        })

        //Event Handler que se activa al hacer click sobre el tipo de teléfono
        // cada vez que le demos click al campo del tipo de teléfono este se convertirá en un dropdown con los tipos de telefonos.
        // #convertir es el id que tiene el elemento que clickamos... cuando se trabaja con tablas de datos dinámicos se utiliza la funcion delegate.
        $("#myTable").delegate("#convertir", "click", function () {
            var select = "<select class='form-control' name='TipoTelefono'><option value='1'>Móvil Móvistar</option><option value='2'>Móvil Claro</option><option value='3'>Planta Móvistar</option><option value='4'>Planta Claro</option></select>";
            $(this).replaceWith(select);
        });
    });
</script>


<div class="row">
    <div class="col-md-10 col-md-offset-1">
        @using (Html.BeginForm("Edit", "Contacto", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <div class="panel panel-default">

                    <div class="panel-heading">
                        <h4 class="text-center">Datos Generales</h4>
                    </div>

                    <div class="panel-body col-md-offset-0">

                        @Html.HiddenFor(model => model.ContactoID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <hr />

                        <div class="form-group">
                            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <hr />

                        <div class="form-group">
                            @Html.LabelFor(model => model.DepartamentoID, "Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("DepartamentoID", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DepartamentoID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr />

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <hr />

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    </div> @*fin panel body*@

                </div> @*fin panel default*@

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="text-center">Números de Contacto</h4>
                    </div>

                    <div class="panel-body col-md-offset-0">

                        <div class="table-responsive">
                            <table class="table table-hover table-striped" id="myTable">
                                <thead>
                                    <tr>
                                        <th class="text-center"> Teléfono </th>
                                        <th class="text-center"> Tipo de Teléfono </th>
                                        <th class="text-center"> Opciones </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                         var telefonos = Model.Telefonos.ToList();
                                    }

                                    @for (var i = 0; i < telefonos.Count; i++)
                                    {
                                        <tr id="@telefonos[i].TelefonoID">
                                            <td>
                                                @Html.TextBoxFor(t => telefonos[i].NumeroTel, new { @class = "form-control text-center" })
                                                @Html.ValidationMessageFor(item => telefonos[i].NumeroTel, "", new { @class = "text-danger" })
                                            </td>

                                            <td>
                                                @Html.TextBoxFor(t => telefonos[i].Descripcion, new { @class = "form-control text-center", id = "convertir" })
                                
                                            </td>

                                            <td class="text-center"> <button type='button' class='btn btn-warning' onclick='return borrarFila(this);'><span class='fa fa-trash-o'></span> Remover </button></td>
                                        </tr>

                                    }
                                </tbody>
                            </table>
                            <hr />

                            <button type="button" id="btnAgregar" class="btn btn-info">Agregar <span class="fa fa-plus-circle"></span></button>

                        </div>




                    </div> @*fin segundo panel body*@


                </div> @*fin segundo panel-default*@




                <div class="panel">
                    <div class="panel-body">
                        <input type="submit" class="btn btn-lg btn-info" value="Actualizar" style="width:49%" id="btnActualizar" />&nbsp;
                        <a class="btn btn-lg btn-danger" href="@Url.Action("Index","Contacto")" style="width:49%">Cancelar</a>
                    </div>
                    
                </div>

            </div> @*fin form horizontal*@
        }


    </div>
</div>

<div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BulkSMSWebApp/Views/Contacto/Index.cshtml
@model BulkSMSWebApp.ViewModels.ContactoCelGrupo
@using BulkSMSWebApp.Helpers;


@{
    ViewBag.Title = "Listado de Contactos";
}

<p>
    <a href="@Url.Action("Create","Contacto")" class="btn btn-info">
        Nuevo Contacto
        <span class="fa fa-fw fa-plus-circle"></span>
    </a>
</p>


<script>

    //function HideDiv()
    //{
    //    $('#DivCarga h5').remove
    //    $('#DivCarga').hide;
    //}

    $(function () {

        var table = $('#myTable').dataTable({
            "lengthMenu": [[4, 10, 20, -1], [4, 10, 20, "Todos"]]
        });

        var tabla = $('#myTable').DataTable()
        var allRows = table.fnGetNodes();

        $('#myTable').delegate(".selected", "click", function () {
            for (var i = 0; i < allRows.length; i++) {
                tabla.rows('.success').nodes().to$().removeClass('success');
            }
            $(this).parents('tr').addClass('success');
        });


        $("#myTable").delegate(".open-dialog", "click", function () {
            var idActual = $(this).data('id');
            $(".idContacto").prepend("<input type='hidden' name='id' value='" + idActual + "'>");
        })

        $("#myTable").delegate(".activar_opendialog", "click", function () {
            var idActual = $(this).data('id');
            $(".idContacto").prepend("<input type='hidden' name='id' value='" + idActual + "'>");
        })

        //$("#myTable").delegate(".detalles", "click", function () {
        //    var idActual = $(this).data('id');
        //    $(".divhidden #contactoid").val(idActual);
        //})
    });
</script>

</br>


<div id="DivCarga" class="alert alert-info alert-dismissable text-center" style="display:none">

    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <img src="~/Images/spiffygif_32x32.gif" />
    <h5><span class="fa fa-info-circle"> </span> Por favor espere mientras se obtienen los resultados de su búsqueda </h5>
</div>

<div class="table-responsive">
    <table class="table table-hover table-striped table-bordered" id="myTable">
        <thead>
            <tr class="label-info">
                <th class="text-center"> Nombres </th>
                <th class="text-center"> Apellidos </th>
                <th class="text-center"> Departamento </th>
                <th class="text-center"> Email </th>
                <th class="text-center"> Estado </th>
                <th class="text-center">Opciones</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Contactos)
            {
                <tr>
                    <td width="16.6%" class="text-center">
                        @Html.DisplayFor(modelItem => item.Nombres)
                    </td>
                    <td width="16.6%" class="text-center">
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>
                    <td width="16.6%" class="text-center">
                        @Html.DisplayFor(modelItem => item.Departamento.NombreDepartameto)
                    </td>
                    <td width="17%" class="text-center">
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td width="16%" class="text-center">
                        @Html.DisplayFor(modelItem => item.Estado.NombreEstado)
                    </td>

                    <td width="16.6%">
                        @Ajax.RawActionLink(string.Format("<span class='fa fa-hand-pointer-o'> Mostrar Teléfonos </span>"), "Index", "Contacto", new { id = item.ContactoID },
                        new AjaxOptions
                        {
                            HttpMethod = "GET",
                            UpdateTargetId = "PhoneList",
                            InsertionMode = InsertionMode.Replace,
                            LoadingElementId = "DivCarga",
                            OnBegin="document.location='#DivCarga'",
                            OnSuccess = "document.location='#PhoneList'"
                        }, new { @class = "selected" })



                        <br />
                        <a href="@Url.Action("Edit", "Contacto", new { id = @item.ContactoID })">
                            <span class="fa fa-edit"></span>
                            Editar
                        </a>
                        <br />

                        @if (item.EstadoID == 1 && User.IsInRole("Administrador"))
                        {
                            <a data-toggle="modal" data-id="@item.ContactoID" class="open-dialog selected" href="#deleteConfirmModal">
                                <span class="fa fa-trash"></span>
                                Desactivar
                            </a>
                        }

                        @if (item.EstadoID == 2 && User.IsInRole("Administrador"))
                        {
                            <a data-toggle="modal" data-id="@item.ContactoID" class="activar_opendialog selected" href="#activeConfirmModal">
                                <span class="fa fa-check"></span>
                                Activar
                            </a>
                        }

                    </td>
                </tr>
            }

        </tbody>

    </table>

</div>

<div id="PhoneList" class="table-responsive">

</div>



@section Modal {

    @{ Html.RenderPartial("_ActivarConfirmationModal"); }
    @{ Html.RenderPartial("_DeleteConfirmationModal"); }


}

@section Scripts{

}