BulkSMSWebApp/Controllers/GrupoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BulkSMSWebApp.DAL;
using BulkSMSWebApp.Models;
using System.Data.SqlClient;
using BulkSMSWebApp.Helpers;
using BulkSMSWebApp.ViewModels;

namespace BulkSMSWebApp.Controllers
{
    public class GrupoController : BaseController
    {
        private BulkSMSContext db = new BulkSMSContext();


       //GET
        public ActionResult ContactosNotInGroup(int? id)
        {
            if (id == null)
            {
                Danger("Error, no se ha encontrado el registro seleccionado", true);
                return View("Index");
            }

            var query = "SELECT T.TelefonoID, C.Nombres+' '+C.Apellidos [Nombres],"
                        + " D.NombreDepartameto, T.NumeroTel, T.Descripcion"
                        + " FROM Contacto C, Telefono T, Departamento D"
                        + " WHERE (C.ContactoID=T.ContactoID and"
                        + " D.DepartamentoID=C.DepartamentoID and T.TelefonoID"
                        + " not in (select T.TelefonoID from GrupoContacto T where T.GrupoID={0}))";

            var contactos = db.Database.SqlQuery<GrupoContacto>(query, id).ToList();
            ViewData["CodGrupo"] = id.Value;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_AgregarContactos", contactos);
            }

            return View();
        }


        //POST
        [Authorize]
        public ActionResult UpdateGrupo(List<int> TelefonoID, int CodGrupo)
        {
            if (TelefonoID == null)
            {
                Danger("Error, no se ha encontrado el registro seleccionado", true);
                return View("Index");
            }
            else
            {
                try
                {
                    foreach (var tel in TelefonoID)
                    {
                        var query = db.Database.ExecuteSqlCommand("INSERT INTO GrupoContacto(GrupoID, TelefonoID) VALUES ({0},{1})", CodGrupo, tel);
                    }

                    var select = "SELECT T.TelefonoID, GR.GrupoID, C.Nombres+' '+C.Apellidos [Nombres],"
                                  + " D.NombreDepartameto, T.NumeroTel, T.Descripcion"
                                  + " FROM Contacto C, Telefono T, GrupoContacto G, Grupo GR , Departamento D"
                                  + " WHERE (C.ContactoID=T.ContactoID and D.DepartamentoID=C.DepartamentoID"
                                  + " and G.TelefonoID=T.TelefonoID and G.GrupoID=GR.GrupoID and C.EstadoID=1 and G.GrupoID={0})";

                    var contactos = db.Database.SqlQuery<GrupoContacto>(select, CodGrupo).ToList();

                    if (Request.IsAjaxRequest())
                    {
                        System.Threading.Thread.Sleep(1500);
                        return PartialView("_contactosGrupos", contactos);
                    }
                }

                catch (Exception ex)
                {
                    Danger("Ha ocurrido un error, por favor contacta al Administrador del Sistema: \n Detalle del error: " + ex.Message);
                    return RedirectToAction("Index");
                }   
            }

            return RedirectToAction("Index");
        }

        //GET
        public ActionResult ContactosGrupo(int? id)
        {

            if (id == null)
            {
                Danger("Error, no se ha encontrado el registro seleccionado", true);
                return View("Index");
            }

            var query = "SELECT T.TelefonoID, GR.GrupoID, C.Nombres+' '+C.Apellidos [Nombres],"
                                  + " D.NombreDepartameto, T.NumeroTel, T.Descripcion"
                                  + " FROM Contacto C, Telefono T, GrupoContacto G, Grupo GR , Departamento D"
                                  + " WHERE (C.ContactoID=T.ContactoID and D.DepartamentoID=C.DepartamentoID"
                                  + " and G.TelefonoID=T.TelefonoID and G.GrupoID=GR.GrupoID and C.EstadoID=1 and G.GrupoID={0})";

            var contactos = db.Database.SqlQuery<GrupoContacto>(query, id).ToList();

            if (Request.IsAjaxRequest())
            {
                System.Threading.Thread.Sleep(2000);
                return PartialView("_contactosGrupos", contactos);
            }

            return View("Index");
        }




        // GET: Grupo
        [NoCache]
        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View(await db.Grupos.ToListAsync());
        }

        // GET: Grupo/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupo grupo = await db.Grupos.FindAsync(id);
            if (grupo == null)
            {
                return HttpNotFound();
            }
            return View(grupo);
        }

        // GET: Grupo/Create
        [Authorize]
        [NoCache]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Grupo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "GrupoID,NombreGrupo,Descripcion")] Grupo grupo, List<int> check)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    grupo.FechaCreacion = DateTime.Now;
                    grupo.EstadoID = 1;
                    db.Grupos.Add(grupo);
                    await db.SaveChangesAsync();

                    foreach (var tel in check)
                    {

                        var query = db.Database.ExecuteSqlCommand("INSERT INTO GrupoContacto(GrupoID, TelefonoID) VALUES ({0},{1})", grupo.GrupoID, tel);
                    }

                    Information(String.Format("El Grupo <b>{0}</b> ha sido registrado correctamente.", grupo.NombreGrupo), true);
                    return RedirectToAction("Create");

                }
                catch (Exception ex)
                {
                    Danger("Ha ocurrido un error en la operación, no se guardaron los cambios!! Por favor contacta al Administrador del Sistema \n Detalles del error: " + ex.Message);
                    return View(grupo);
                }
            }

            return View(grupo);
        }

        // GET: Grupo/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Grupo grupo = await db.Grupos.FindAsync(id);
            if (grupo == null)
            {
                return HttpNotFound();
            }
     
            System.Threading.Thread.Sleep(1500);
            return PartialView("_EditGrupo", grupo);
        }

        // POST: Grupo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "GrupoID,NombreGrupo,Descripcion,FechaCreacion")] Grupo grupo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    grupo.EstadoID = 1;
                    db.Entry(grupo).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    var grupos = db.Grupos.ToList();
                    System.Threading.Thread.Sleep(1000);
                    return PartialView("_IndexPartialView", grupos);
                }
                catch (Exception ex)
                {
 
                }
                
            }
            return View(grupo);
        }

        // GET: Grupo/Delete/5
        //[Authorize]
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Grupo grupo = await db.Grupos.FindAsync(id);
        //    if (grupo == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(grupo);
        //}

        // POST: Grupo/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Delete(int id)
        //{
        //    Grupo grupo = await db.Grupos.FindAsync(id);
        //    db.Grupos.Remove(grupo);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        public ActionResult BorrarContactos(List<int> TelefonoID, int CodGrupo)
        {
            if (TelefonoID == null)
            {
                Danger("Error, no se ha encontrado el registro seleccionado", true);
                return View("Index");
            }
            else
            {
                try
                {
                    foreach (var tel in TelefonoID)
                    {
                        var query = db.Database.ExecuteSqlCommand("DELETE FROM GrupoContacto WHERE GrupoID = {0} AND TelefonoID = {1}", CodGrupo, tel);
                    }

                    var select = "SELECT GR.GrupoID, C.Nombres+' '+C.Apellidos [Nombres],"
                                  + " D.NombreDepartameto, T.NumeroTel, T.Descripcion"

BulkSMSWebApp/Views/Shared/_Alert.cshtml
@using BulkSMSWebApp.Helpers
@{
    var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

    if (alerts.Any())
    {
        @*<hr />*@
    }

    foreach (var alert in alerts)
    {
        var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
        <div id="success-alert" class="alert alert-@alert.AlertStyle @dismissableClass text-center">
            @if (alert.Dismissable)
            {
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            }
            <span class="fa @alert.alertIcon"> @Html.Raw(@alert.Message) </span>
        </div>
    }
}

BulkSMSWebApp/Views/Shared/_Header.cshtml
<img src="~/Images/Header.png" class="img-responsive" width="100%" />

<div class="navbar navbar-default" role="navigation">
 
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
       

        <a class="" href="index.html"><span class="navbar-brand"><span class="fa fa-paper-plane"></span> Plataforma SMS</span></a>
    </div>
    @using Microsoft.AspNet.Identity
    <div class="navbar-collapse collapse" style="height: 1px;">
      
        <ul id="main-menu" class="nav navbar-nav navbar-right">
            @Html.Partial("_LoginPartial")
            @*<li class="dropdown col-xs-12">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-user padding-right-small" style="position:relative;top: 3px;"></span> Welcome 
                    <i class="fa fa-caret-down"></i>
                </a>

                <ul class="dropdown-menu">
  
                
                    <li><a tabindex="-1" href="sign-in.html">Logout</a></li>
                </ul>
            </li>*@
        </ul>

    </div>
</div>

BulkSMSWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BulkSMSIdeay</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jquery-ajax")
    @Scripts.Render("~/bundles/jqueryDataTable")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                     <li>@Html.ActionLink("Contactos","Index","Contacto")</li>
                     <li>@Html.ActionLink("Mensajes", "Index", "Mensaje")</li>
            
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
      
           
                @{ Html.RenderPartial("_Alert"); }

                @RenderBody()
           
           
       
      
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Equipos y Sistemas S.A</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

  

</body>
</html>

BulkSMSWebApp/Views/Shared/_LoginPage.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Plataforma SMS IDEAY</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
</head>

<body class=" theme-blue">

    <img src="~/Images/Header.png" class="img-responsive" width="100%" />
    <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <span style="color:white;" class="navbar-brand"><span class="fa fa-fw fa-paper-plane"></span>Plataforma SMS</span>
        </div>

        <div class="navbar-collapse collapse" style="height: 1px;">

        </div>
    </div>

    <div class="dialog">

        @*Login content here*@
        @{ Html.RenderPartial("_Alert"); }
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">

        // le agrega un * a todos los elementos que sean required



        //Evita que el navegador retroceda el historial cuando se presiona la Tecla BackSpace
        $(document).unbind('keydown').bind('keydown', function (event) {
            var doPrevent = false;
            if (event.keyCode === 8) {
                var d = event.srcElement || event.target;
                if ((d.tagName.toUpperCase() === 'INPUT' &&
                     (
                         d.type.toUpperCase() === 'TEXT' ||
                         d.type.toUpperCase() === 'PASSWORD' ||
                         d.type.toUpperCase() === 'FILE' ||
                         d.type.toUpperCase() === 'EMAIL' ||
                         d.type.toUpperCase() === 'SEARCH' ||
                         d.type.toUpperCase() === 'DATE')
                     ) ||
                     d.tagName.toUpperCase() === 'TEXTAREA') {
                    doPrevent = d.readOnly || d.disabled;
                }
                else {
                    doPrevent = true;
                }
            }

            if (doPrevent) {
                event.preventDefault();
            }
        });

        //oculta automáticamente la alerta que se muestra
        $("#success-alert").fadeTo(5000, 400).slideUp(400, function () {
            $("#success-alert").alert('close');
        });

    </script>


</body>

</html>

BulkSMSWebApp/Views/Shared/_MasterPage.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Plataforma SMS IDEAY</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/MasterPage/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/js")

    <script type="text/javascript">
        $(function () {
            $(".knob").knob();
        });
    </script>
</head>

<body class="theme-blue">
    @RenderSection("Modal", required: false)

    <style type="text/css">
        .navbar-default .navbar-brand, .navbar-default .navbar-brand:hover {
            color: #fff;
        }

        #span {
            color: white !important;
        }
    </style>

    <script type="text/javascript">
        $(function () {
            var uls = $('.sidebar-nav > ul > *').clone();
            uls.addClass('visible-xs');
            $('#main-menu').append(uls.clone());
        });
    </script>


    @Html.Partial("_Header")

    @Html.Partial("_Navegacion")


    <div class="content">
        <div class="header text-center">

            <h1 class="page-title">@ViewBag.Title</h1>

            @if (ViewBag.Title.ToString().ToUpper().Contains("REGISTRAR") || ViewBag.Title.ToString().ToUpper().Contains("CREAR")
                    || ViewBag.Title.ToString().ToUpper().Contains("ENVIAR"))
            {
                <p>Los Campos con el símbolo <strong class="text-danger"> * </strong> son obligatorios</p>
            }
            @*<hr />*@

        </div>

        @*En este Div se carga el modal cuando se va a actualizar un grupo o los miembros de un grupo*@
        <div class="modal fade" id="agregarContactos" tabindex="-1" role="dialog" aria-labelledby="updateGroup" aria-hidden="true">
            <div id="edit-container">

            </div>
        </div>


        @{ Html.RenderPartial("_Alert"); }
        @RenderBody()


        <div class="footer">
            @*<footer> *@
            <hr>
            <p class="text-center">© @DateTime.Now.Year Equipos y Sistemas S.A </p>
            @*</footer>*@
        </div>

    </div>



    @RenderSection("scripts", required: false)


    <script type="text/javascript">

        // le agrega un * de color rojo a todos los elementos que sean required
        // y tengan asociado un label a travez de su id.

        $('*').each(function () {
            var req = $(this).attr('data-val-required');
            if (undefined != req) {
                var label = $('label[for="' + $(this).attr('id') + '"]');
                var text = label.text();
                if (text.length > 0) {
                    label.append('<span style="color:red"> *</span>');
                }
            }
        });


        //Evita que el navegador retroceda el historial cuando se presiona la Tecla de Retorno
        $(document).unbind('keydown').bind('keydown', function (event) {
            var doPrevent = false;
            if (event.keyCode === 8) {
                var d = event.srcElement || event.target;
                if ((d.tagName.toUpperCase() === 'INPUT' &&
                     (
                         d.type.toUpperCase() === 'TEXT' ||
                         d.type.toUpperCase() === 'PASSWORD' ||
                         d.type.toUpperCase() === 'FILE' ||
                         d.type.toUpperCase() === 'EMAIL' ||
                         d.type.toUpperCase() === 'SEARCH' ||
                         d.type.toUpperCase() === 'DATE')
                     ) ||
                     d.tagName.toUpperCase() === 'TEXTAREA') {
                    doPrevent = d.readOnly || d.disabled;
                }
                else {
                    doPrevent = true;
                }
            }

            if (doPrevent) {
                event.preventDefault();
            }
        });

        //oculta automáticamente despues de 5 segundos la alerta que se muestra despues de cada operación
        $("#success-alert").fadeTo(5000, 400).slideUp(400, function () {
            $("#success-alert").alert('close');
        });

    </script>


    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
</body>
</html>

BulkSMSWebApp/Views/Shared/_Navegacion.cshtml
@using Microsoft.AspNet.Identity
@using BulkSMSWebApp.Helpers;
<div class="sidebar-nav">
    <ul>
        <li><a href="@Url.Action("Index","Home")" class="nav-header"><i class="fa fa-fw fa-2x fa-home"></i> Inicio </a></li>

        <li><a href="javascript:void(0);" data-target=".dashboard-menu" class="nav-header" data-toggle="collapse"><i class="fa fa-fw fa-users fa-2x"></i> Contactos @*<i class="fa fa-collapse"></i>*@ <span class="label label-info">+2</span></a></li>
        <li>
            <ul class="dashboard-menu nav nav-list collapse">
                <li>
                    <a href="@Url.Action("Create","Contacto")" class="btn btn-navbar">
                        Nuevo Contacto
                        <span class="fa fa-fw fa-2x fa-user-plus"></span>
                    </a>
                </li>
            </ul>

            <ul class="dashboard-menu nav nav-list collapse">
                <li>
                    <a href="@Url.Action("Index","Contacto")" class="btn btn-navbar">
                        Mostrar Contactos
                        <span class="fa fa-fw fa-2x fa-edit"></span>
                    </a>
                </li>
            </ul>

        </li>

        <li><a href="javascript:void(0);" data-target=".accounts-menu" class="nav-header collapsed" data-toggle="collapse"><i class="fa fa-fw fa-object-group fa-2x"></i> Grupos <span class="label label-info">+2</span></a></li>
        <li>
            <ul class="accounts-menu nav nav-list collapse">
                <li>
                    <a href="@Url.Action("Create","Grupo")" class="btn btn-navbar">
                        Nuevo Grupo
                        <span class="fa fa-fw fa-2x fa-plus-circle"></span>
                    </a>
                </li>
            </ul>

            <ul class="accounts-menu nav nav-list collapse">
                <li>
                    <a href="@Url.Action("Index","Grupo")" class="btn btn-navbar">
                        Mostrar Grupos
                        <span class="fa fa-fw fa-2x fa-edit"></span>
                    </a>
                </li>
            </ul>
        </li>

        <li><a href="javascript:void(0);" data-target=".message-menu" class="nav-header collapsed" data-toggle="collapse"><i class="fa fa-fw fa-envelope fa-2x"></i> Mensajes <span class="label label-info">+2</span></a></li>
        <li>
            <ul class="message-menu nav nav-list collapse">
                <li>
                    <a href="@Url.Action("Create","Mensaje")" class="btn btn-navbar">
                        Nuevo Mensaje
                        <span class="fa fa-fw fa-2x fa-plus-circle"></span>
                    </a>
                </li>
            </ul>

            <ul class="message-menu nav nav-list collapse">
                <li>
                    <a href="@Url.Action("Index","Mensaje")" class="btn btn-navbar">
                        Mostrar Mensajes
                        <span class="fa fa-fw fa-2x fa-edit"></span>
                    </a>
                </li>
            </ul>

  

        </li>

        @if (Request.IsAuthenticated && User.IsInRole("Administrador"))
        {
            <li><a href="javascript:void(0);" data-target=".users-menu" class="nav-header collapsed" data-toggle="collapse"><i class="fa fa-fw fa-users fa-2x"></i> Usuarios <span class="label label-info">+2</span></a></li>
            <li>
                <ul class="users-menu nav nav-list collapse">
                    <li>
                        <a href="@Url.Action("Register","Account")" class="btn btn-navbar">
                            Nuevo Usuario
                            <span class="fa fa-fw fa-2x fa-plus-circle"></span>
                        </a>
                    </li>
                </ul>

                <ul class="users-menu nav nav-list collapse">
                    <li>
                        <a href="@Url.Action("UserList","Account")" class="btn btn-navbar">
                            Mostrar Usuarios
                            <span class="fa fa-fw fa-2x fa-edit"></span>
                        </a>
                    </li>
                </ul>
            </li>
        }




    </ul>
</div>